version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    restart: unless-stopped
